name: Check Schema
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  check_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install JSkiner
          pip install black
          pip install tqdm
          pip install blosc
          pip install scalable-cuckoo-filter
      - name: Run JSkiner 
        run: jskiner --in-path data/latest --nworkers 4 --verbose true --out data/latest.schema --batch-size 1000 --cuckoo-path data/latest.cuckoo --cuckoo-size 50000000 --cuckoo-fpr 0.1 --sample-size 10000
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest.schema
          git add data/latest.cuckoo
          git diff-index --quiet HEAD || git commit -m 'update: package latest schema'
      - name: Git Push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push origin main
