name: Check Schema
on: push
jobs:
  check_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install JSkiner
          pip install autopep8
          pip install tqdm
          pip install jsonschema-inference
      - name: Run json merge
        run : python merge_latest.py
      - name: Run JSkiner 
        run: jsonschema-inference --jsonl data/latest.jsonl --nworkers 2 --verbose 1 --out data/latest.schema
      - name: Autopep
        run: autopep8 --in-place --aggressive data/latest.schema
      - name: Git commit
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest.schema
          git diff-index --quiet HEAD || git commit -m 'update: package latest json schema'
      - name: Git ush
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push origin main