name: Do Update
on: push
#  schedule:
#    - cron: "0 0 * * *"
jobs:
  update_package_names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install beautifulsoup4==4.12.0
          pip install requests==2.28.2
      - name: Run update script 
        run : |
         python update_package_names.py
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data
          git diff-index --quiet HEAD || git commit -m 'update: package names'
      - name: Git Push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push origin main          
  update_latest_json:
    name: Upload Latest Json for Each Package
    needs: update_package_names
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        alpha: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run install
        run: |
          pip install requests==2.28.2
      - name: New Branch
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push origin -d update_latest/${{ matrix.alpha }} --quiet || echo 'update_latest/${{ matrix.alpha }} already removed'
          git checkout -b update_latest/${{ matrix.alpha }}
          git push --set-upstream origin update_latest/${{ matrix.alpha }}
      - name: Run update script
        run: python update_latest_all.py ${{ matrix.alpha }}
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest
          git diff-index --quiet HEAD || git commit -m 'update: package latest json'
      - name: Git Push
        run: |
          git push origin update_latest/${{ matrix.alpha }}
  merge_n_push:
    name: Merge Updated Branches of all Latest Package
    needs: update_latest_json
    if: always()
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        branches: ['0 1 2 3 4 5 6 7 8 9 a b c d e f g h i j k l m n o p q r s t u v w x y z']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Git Pull Main
        run: |
          git config --global user.email "jeffrey82221@gmail.com"
          git config --global user.name "jeffrey82221"
          git config pull.rebase false
          git pull origin main
          git checkout main
      - name: Git Merge
        run: | 
          for VARIABLE in ${{ matrix.branches }}
          do
              git pull --squash origin update_latest/$VARIABLE || echo 'update_latest/$VARIABLE does not exists'
              git add data/latest || echo 'git add nothing $VARIABLE'
              git commit -m 'update: latest json of package in $VARIABLE' || echo 'git add nothing $VARIABLE'
          done
        shell: bash
      - name: Git Push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push origin main || echo 'git push origin main nothing'
      - name: Git Delete
        if: always()
        run: |
          for VARIABLE in ${{ matrix.branches }}
          do
              git push origin -d update_latest/$VARIABLE || echo 'git delete $VARIABLE nothing'
          done
          
