name: Do Update
on: push
#  schedule:
#    - cron: "0 0 * * *"
jobs:
  update_package_names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: |
          pip install beautifulsoup4==4.12.0
          pip install requests==2.28.2
      - name: Run update script 
        run : |
         python update_package_names.py
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data
          git diff-index --quiet HEAD || git commit -m 'update: package names'
      - name: Git Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
  update_latest_json:
    name: Upload Latest Json for Each Package
    needs: update_package_names
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpha: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run update script
        run: |
          chmod 777 update_latest_all.sh
          ./update_latest_all.sh {{ matrix.alpha }}
      - name: Git Commit 
        run: |
          git config --global user.name "jeffrey82221"
          git config --global user.email "jeffrey82221@gmail.com"
          git add data/latest
          git diff-index --quiet HEAD || git commit -m 'update: package latest json'
      - name: Git Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}