name: Continuous Integration
on: push
jobs:
  update_package_names:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install package
        run: pip install -r requirements.txt
      - name: Run update script 
        run : |
         python update_package_names.py
      - name: Git commit and push
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m 'update: package names'
          git push
      